// Generated code from Butter Knife. Do not modify!
package com.bop.zz;

import android.view.View;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.Injector;

public class ConfigChoiseActivity$$ViewInjector<T extends com.bop.zz.ConfigChoiseActivity> implements Injector<T> {
  @Override public void inject(final Finder finder, final T target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131361960, "field 'mCbShowCamera'");
    target.mCbShowCamera = finder.castView(view, 2131361960, "field 'mCbShowCamera'");
    view = finder.findRequiredView(source, 2131361959, "field 'mCbOpenForceCropEdit'");
    target.mCbOpenForceCropEdit = finder.castView(view, 2131361959, "field 'mCbOpenForceCropEdit'");
    view = finder.findRequiredView(source, 2131361940, "field 'mRbFresco'");
    target.mRbFresco = finder.castView(view, 2131361940, "field 'mRbFresco'");
    view = finder.findRequiredView(source, 2131361931, "field 'mRbThemeCustom'");
    target.mRbThemeCustom = finder.castView(view, 2131361931, "field 'mRbThemeCustom'");
    view = finder.findRequiredView(source, 2131361932, "field 'mRbThemeCyan'");
    target.mRbThemeCyan = finder.castView(view, 2131361932, "field 'mRbThemeCyan'");
    view = finder.findRequiredView(source, 2131361937, "field 'mRbUil'");
    target.mRbUil = finder.castView(view, 2131361937, "field 'mRbUil'");
    view = finder.findRequiredView(source, 2131361945, "field 'mLlMaxSize'");
    target.mLlMaxSize = finder.castView(view, 2131361945, "field 'mLlMaxSize'");
    view = finder.findRequiredView(source, 2131361962, "field 'mCbNoAnimation'");
    target.mCbNoAnimation = finder.castView(view, 2131361962, "field 'mCbNoAnimation'");
    view = finder.findRequiredView(source, 2131361946, "field 'mEtMaxSize'");
    target.mEtMaxSize = finder.castView(view, 2131361946, "field 'mEtMaxSize'");
    view = finder.findRequiredView(source, 2131361963, "field 'mBtnOpenGallery'");
    target.mBtnOpenGallery = finder.castView(view, 2131361963, "field 'mBtnOpenGallery'");
    view = finder.findRequiredView(source, 2131361956, "field 'mCbCropSquare'");
    target.mCbCropSquare = finder.castView(view, 2131361956, "field 'mCbCropSquare'");
    view = finder.findRequiredView(source, 2131361950, "field 'mCbRotate'");
    target.mCbRotate = finder.castView(view, 2131361950, "field 'mCbRotate'");
    view = finder.findRequiredView(source, 2131361936, "field 'mRbThemeDark'");
    target.mRbThemeDark = finder.castView(view, 2131361936, "field 'mRbThemeDark'");
    view = finder.findRequiredView(source, 2131361935, "field 'mRbThemeTeal'");
    target.mRbThemeTeal = finder.castView(view, 2131361935, "field 'mRbThemeTeal'");
    view = finder.findRequiredView(source, 2131361957, "field 'mLlForceCrop'");
    target.mLlForceCrop = finder.castView(view, 2131361957, "field 'mLlForceCrop'");
    view = finder.findRequiredView(source, 2131361934, "field 'mRbThemeGreen'");
    target.mRbThemeGreen = finder.castView(view, 2131361934, "field 'mRbThemeGreen'");
    view = finder.findRequiredView(source, 2131361933, "field 'mRbThemeOrange'");
    target.mRbThemeOrange = finder.castView(view, 2131361933, "field 'mRbThemeOrange'");
    view = finder.findRequiredView(source, 2131361930, "field 'mRbThemeDefault'");
    target.mRbThemeDefault = finder.castView(view, 2131361930, "field 'mRbThemeDefault'");
    view = finder.findRequiredView(source, 2131361949, "field 'mCbCrop'");
    target.mCbCrop = finder.castView(view, 2131361949, "field 'mCbCrop'");
    view = finder.findRequiredView(source, 2131361958, "field 'mCbOpenForceCrop'");
    target.mCbOpenForceCrop = finder.castView(view, 2131361958, "field 'mCbOpenForceCrop'");
    view = finder.findRequiredView(source, 2131361955, "field 'mEtCropHeight'");
    target.mEtCropHeight = finder.castView(view, 2131361955, "field 'mEtCropHeight'");
    view = finder.findRequiredView(source, 2131361939, "field 'mRbPicasso'");
    target.mRbPicasso = finder.castView(view, 2131361939, "field 'mRbPicasso'");
    view = finder.findRequiredView(source, 2131361954, "field 'mEtCropWidth'");
    target.mEtCropWidth = finder.castView(view, 2131361954, "field 'mEtCropWidth'");
    view = finder.findRequiredView(source, 2131361953, "field 'mLlCropSize'");
    target.mLlCropSize = finder.castView(view, 2131361953, "field 'mLlCropSize'");
    view = finder.findRequiredView(source, 2131361951, "field 'mCbCropReplaceSource'");
    target.mCbCropReplaceSource = finder.castView(view, 2131361951, "field 'mCbCropReplaceSource'");
    view = finder.findRequiredView(source, 2131361952, "field 'mCbRotateReplaceSource'");
    target.mCbRotateReplaceSource = finder.castView(view, 2131361952, "field 'mCbRotateReplaceSource'");
    view = finder.findRequiredView(source, 2131361944, "field 'mRbMutiSelect'");
    target.mRbMutiSelect = finder.castView(view, 2131361944, "field 'mRbMutiSelect'");
    view = finder.findRequiredView(source, 2131361938, "field 'mRbGlide'");
    target.mRbGlide = finder.castView(view, 2131361938, "field 'mRbGlide'");
    view = finder.findRequiredView(source, 2131361964, "field 'mLvPhoto'");
    target.mLvPhoto = finder.castView(view, 2131361964, "field 'mLvPhoto'");
    view = finder.findRequiredView(source, 2131361948, "field 'mLlEdit'");
    target.mLlEdit = finder.castView(view, 2131361948, "field 'mLlEdit'");
    view = finder.findRequiredView(source, 2131361947, "field 'mCbEdit'");
    target.mCbEdit = finder.castView(view, 2131361947, "field 'mCbEdit'");
    view = finder.findRequiredView(source, 2131361942, "field 'mRbXutils'");
    target.mRbXutils = finder.castView(view, 2131361942, "field 'mRbXutils'");
    view = finder.findRequiredView(source, 2131361943, "field 'mRbSingleSelect'");
    target.mRbSingleSelect = finder.castView(view, 2131361943, "field 'mRbSingleSelect'");
    view = finder.findRequiredView(source, 2131361941, "field 'mRbXutils3'");
    target.mRbXutils3 = finder.castView(view, 2131361941, "field 'mRbXutils3'");
    view = finder.findRequiredView(source, 2131361961, "field 'mCbPreview'");
    target.mCbPreview = finder.castView(view, 2131361961, "field 'mCbPreview'");
  }

  @Override public void reset(T target) {
    target.mCbShowCamera = null;
    target.mCbOpenForceCropEdit = null;
    target.mRbFresco = null;
    target.mRbThemeCustom = null;
    target.mRbThemeCyan = null;
    target.mRbUil = null;
    target.mLlMaxSize = null;
    target.mCbNoAnimation = null;
    target.mEtMaxSize = null;
    target.mBtnOpenGallery = null;
    target.mCbCropSquare = null;
    target.mCbRotate = null;
    target.mRbThemeDark = null;
    target.mRbThemeTeal = null;
    target.mLlForceCrop = null;
    target.mRbThemeGreen = null;
    target.mRbThemeOrange = null;
    target.mRbThemeDefault = null;
    target.mCbCrop = null;
    target.mCbOpenForceCrop = null;
    target.mEtCropHeight = null;
    target.mRbPicasso = null;
    target.mEtCropWidth = null;
    target.mLlCropSize = null;
    target.mCbCropReplaceSource = null;
    target.mCbRotateReplaceSource = null;
    target.mRbMutiSelect = null;
    target.mRbGlide = null;
    target.mLvPhoto = null;
    target.mLlEdit = null;
    target.mCbEdit = null;
    target.mRbXutils = null;
    target.mRbSingleSelect = null;
    target.mRbXutils3 = null;
    target.mCbPreview = null;
  }
}
